function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double representing the validation accuracy as
%       a percentage. In the app, the Models pane displays the validation
%       accuracy for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   [yfit,scores] = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 30-Dec-2025 11:17:34


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
trainingData = readtable('Web_browse_all.csv');
inputTable = trainingData;
predictorNames = {'MediaID', 'MediaName', 'MediaDuration_sec_U_UserControlled_', 'AOIID', 'AOIName', 'AOIStart', 'AOIDuration_sec_U_UserControlled_', 'UserID', 'UserName', 'UserGender', 'UserAge', 'TimeTo1stView_sec_', 'TimeViewed_sec_', 'TimeViewed___', 'Fixations___', 'Revisits___'};
predictors = inputTable(:, predictorNames);
response = inputTable.Group;
isCategoricalPredictor = [false, true, false, false, true, false, false, false, true, true, false, false, false, false, false, false];
classNames = categorical({'ASD'; 'Control'});

% Data transformation: Select subset of the features
% This code selects the same subset of features as were used in the app.
includedPredictorNames = predictors.Properties.VariableNames([true false false true false false false true false true false true true true true true]);
predictors = predictors(:,includedPredictorNames);
isCategoricalPredictor = isCategoricalPredictor([true false false true false false false true false true false true true true true true]);

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationNeuralNetwork = fitcnet(...
    predictors, ...
    response, ...
    'LayerSizes', 100, ...
    'Activations', 'relu', ...
    'Lambda', 0, ...
    'IterationLimit', 1000, ...
    'Standardize', true, ...
    'ClassNames', classNames);

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
featureSelectionFcn = @(x) x(:,includedPredictorNames);
neuralNetworkPredictFcn = @(x) predict(classificationNeuralNetwork, x);
trainedClassifier.predictFcn = @(x) neuralNetworkPredictFcn(featureSelectionFcn(predictorExtractionFcn(x)));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'AOIDuration_sec_U_UserControlled_', 'AOIID', 'AOIName', 'AOIStart', 'Fixations___', 'MediaDuration_sec_U_UserControlled_', 'MediaID', 'MediaName', 'Revisits___', 'TimeTo1stView_sec_', 'TimeViewed___', 'TimeViewed_sec_', 'UserAge', 'UserGender', 'UserID', 'UserName'};
trainedClassifier.ClassificationNeuralNetwork = classificationNeuralNetwork;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2025b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  [yfit,scores] = c.predictFcn(T) \nreplace ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'MediaID', 'MediaName', 'MediaDuration_sec_U_UserControlled_', 'AOIID', 'AOIName', 'AOIStart', 'AOIDuration_sec_U_UserControlled_', 'UserID', 'UserName', 'UserGender', 'UserAge', 'TimeTo1stView_sec_', 'TimeViewed_sec_', 'TimeViewed___', 'Fixations___', 'Revisits___'};
predictors = inputTable(:, predictorNames);
response = inputTable.Group;
isCategoricalPredictor = [false, true, false, false, true, false, false, false, true, true, false, false, false, false, false, false];
classNames = categorical({'ASD'; 'Control'});

% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationNeuralNetwork, 'KFold', 50);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');


%GFF Loss 
kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
% Display the validation accuracy
fprintf('Validation Accuracy: %.2f%%\n', validationAccuracy * 100);

disp('Cross Entropy:');
kfoldLoss(partitionedModel, 'LossFun', 'crossentropy')
 



