function [trainedClassifier, validationAccuracy] = trainClassifierSearch(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double representing the validation accuracy as
%       a percentage. In the app, the Models pane displays the validation
%       accuracy for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   [yfit,scores] = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 30-Dec-2025 14:42:34


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
trainingData = readtable('Web_search_all.csv');
inputTable = trainingData;
predictorNames = {'MediaID', 'AOIID', 'UserID', 'UserGender', 'TimeTo1stView_sec_', 'TimeViewed_sec_', 'TimeViewed___', 'Fixations___', 'Revisits___'};
predictors = inputTable(:, predictorNames);
response = inputTable.Group;
isCategoricalPredictor = [false, false, false, true, false, false, false, false, false];
classNames = categorical({'ASD'; 'Control'});

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationNeuralNetwork = fitcnet(...
    predictors, ...
    response, ...
    'LayerSizes', [25 10], ...
    'Activations', 'relu', ...
    'Lambda', 0, ...
    'IterationLimit', 1000, ...
    'Standardize', true, ...
    'ClassNames', classNames);

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
neuralNetworkPredictFcn = @(x) predict(classificationNeuralNetwork, x);
trainedClassifier.predictFcn = @(x) neuralNetworkPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'AOIID', 'Fixations___', 'MediaID', 'Revisits___', 'TimeTo1stView_sec_', 'TimeViewed___', 'TimeViewed_sec_', 'UserGender', 'UserID'};
trainedClassifier.ClassificationNeuralNetwork = classificationNeuralNetwork;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2025b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  [yfit,scores] = c.predictFcn(T) \nreplace ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'MediaID', 'AOIID', 'UserID', 'UserGender', 'TimeTo1stView_sec_', 'TimeViewed_sec_', 'TimeViewed___', 'Fixations___', 'Revisits___'};
predictors = inputTable(:, predictorNames);
response = inputTable.Group;
isCategoricalPredictor = [false, false, false, true, false, false, false, false, false];
classNames = categorical({'ASD'; 'Control'});

% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationNeuralNetwork, 'KFold', 50);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');


%GFF Loss 
kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
% Display the validation accuracy
fprintf('Validation Accuracy: %.2f%%\n', validationAccuracy * 100);

disp('Cross Entropy:');
kfoldLoss(partitionedModel, 'LossFun', 'crossentropy')

%GFF

response = categorical(response);
validationPredictions = categorical(validationPredictions);


% Compute the confusion matrix
confusionMat = confusionmat(response, validationPredictions);

% Display the confusion matrix
disp('Confusion Matrix:');
disp(confusionMat);

% Calculate and display the classification metrics
TP = confusionMat(1,1); % True Positives
TN = confusionMat(2,2); % True Negatives
FP = confusionMat(1,2); % False Positives
FN = confusionMat(2,1); % False Negatives

accuracy = (TP + TN) / sum(confusionMat(:));
precision = TP / (TP + FP);
recall = TP / (TP + FN);
f1Score = 2 * (precision * recall) / (precision + recall);

fprintf('Accuracy: %.2f%%\n', accuracy * 100);
fprintf('Precision: %.2f%%\n', precision * 100);
fprintf('Recall: %.2f%%\n', recall * 100);
fprintf('F1 Score: %.2f\n', f1Score);


% Plot the confusion matrix
figure;
cm=confusionchart(confusionMat, classNames);
cm.RowSummary = 'row-normalized';
title('Confusion Matrix');

